// @generated by AI Solution Builder (non-destructive)
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { Layers, Database, Sparkles, Activity, Search, TrendingUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const ENTITY_ROUTES: [string, string][] = [["invoices", "invoices"], ["expenses", "expenses"]];

function KpiCard({
  label,
  value,
  icon,
}: {
  label: string;
  value: string | number;
  icon?: React.ReactNode;
}) {
  return (
    <Card className="gap-2">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
          {label}
        </CardTitle>
        {icon}
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold tabular-nums text-foreground">{value}</div>
      </CardContent>
    </Card>
  );
}

export default function Dashboard() {
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [filter, setFilter] = useState("");
  const [analytics, setAnalytics] = useState<{
    available: boolean;
    total: number;
    average: number;
    count: number;
    metric?: string;
    trend: { date: string; total: number }[];
  } | null>(null);

  useEffect(() => {
    (async () => {
      for (const [name, path] of ENTITY_ROUTES) {
        try {
          const rows = await api.get<unknown[]>(`/${path}`);
          setCounts((c) => ({ ...c, [name]: rows.length }));
        } catch {
          setCounts((c) => ({ ...c, [name]: 0 }));
        }
      }
    })();
    api
      .get<{
        available: boolean;
        total: number;
        average: number;
        count: number;
        metric?: string;
        trend: { date: string; total: number }[];
      }>("/analytics/summary")
      .then(setAnalytics)
      .catch(() => setAnalytics(null));
  }, []);

  const totalRecords = Object.values(counts).reduce((a, b) => a + b, 0);
  const visibleRoutes = ENTITY_ROUTES.filter(([name]) =>
    name.toLowerCase().includes(filter.toLowerCase())
  );

  return (
    <main className="min-h-screen bg-background px-4 py-8 text-foreground sm:px-6 md:py-12">
      <div className="mx-auto max-w-6xl">
        {/* Animated Hero Header */}
        <div className="animate-in fade-in duration-300">
          <Card className="gap-6 overflow-hidden p-6 md:p-8">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div className="min-w-0">
                <div className="mb-2 flex flex-wrap items-center gap-2">
                  <Badge>Production Prototype</Badge>
                  <Badge variant="secondary">Live API</Badge>
                </div>
                <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl">
                  Subtrack
                </h1>
                <p className="mt-2 max-w-2xl text-sm text-muted-foreground">Subtrack dashboard</p>
              </div>

              <Button asChild variant="outline" size="sm" className="shrink-0">
                <Link href="/api/docs">API Docs</Link>
              </Button>
            </div>

            {/* Real Analytics KPIs & Chart or Quick Metrics Bar */}
            {analytics?.available ? (
              <div className="border-t border-border pt-6">
                <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
                  <KpiCard
                    label={`Total ${analytics.metric || "Volume"}`}
                    value={analytics.total.toLocaleString()}
                    icon={<Layers className="h-4 w-4 text-primary" />}
                  />
                  <KpiCard
                    label="Average"
                    value={analytics.average.toFixed(2)}
                    icon={<Activity className="h-4 w-4 text-primary" />}
                  />
                  <KpiCard
                    label="Records"
                    value={analytics.count.toLocaleString()}
                    icon={<Database className="h-4 w-4 text-primary" />}
                  />
                </div>
                {analytics.trend && analytics.trend.length > 0 && (
                  <Card>
                    <CardHeader className="pb-3">
                      <div className="flex items-center justify-between">
                        <CardTitle className="text-xs font-medium text-muted-foreground">
                          Activity &amp; Volume Distribution
                        </CardTitle>
                        <TrendingUp className="h-4 w-4 text-primary" />
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div className="flex items-end gap-2 h-28 pt-4">
                        {analytics.trend.slice(-12).map((point, pIdx) => (
                          <div key={pIdx} className="flex-1 flex flex-col items-center gap-1.5 h-full justify-end group">
                            <div
                              className="w-full bg-primary/20 group-hover:bg-primary transition-colors rounded-t"
                              style={{
                                height: `${Math.max(15, Math.min(100, (point.total / (analytics.total || 1)) * 100))}%`,
                              }}
                            />
                            <span className="text-[10px] text-muted-foreground truncate w-full text-center">
                              {point.date.slice(5)}
                            </span>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                )}
              </div>
            ) : (
              <div className="grid grid-cols-2 gap-4 border-t border-border pt-6 sm:grid-cols-3">
                <KpiCard
                  label="Modules"
                  value={ENTITY_ROUTES.length}
                  icon={<Layers className="h-4 w-4 text-primary" />}
                />
                <KpiCard
                  label="Total Records"
                  value={totalRecords}
                  icon={<Database className="h-4 w-4 text-primary" />}
                />
                <KpiCard
                  label="API Status"
                  value="Live"
                  icon={<Activity className="h-4 w-4 text-primary" />}
                />
              </div>
            )}
          </Card>
        </div>

        {/* Search & Header */}
        <div className="mt-10 flex flex-wrap items-center justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold tracking-tight text-foreground">
              Application Modules
            </h2>
            <p className="text-xs text-muted-foreground">
              Manage data models and business logic workflows
            </p>
          </div>

          <div className="relative w-full max-w-xs">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              type="text"
              placeholder="Search modules..."
              aria-label="Search modules"
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
              className="pl-9"
            />
          </div>
        </div>

        {/* Animated Cards Grid */}
        {visibleRoutes.length === 0 ? (
          <Card className="mt-6">
            <CardContent className="flex flex-col items-center gap-2 py-12 text-center">
              <Search className="h-6 w-6 text-muted-foreground" />
              <CardTitle className="text-base">No modules match "{filter}"</CardTitle>
              <CardDescription>Clear the search to see every module in this app.</CardDescription>
            </CardContent>
          </Card>
        ) : (
        <div className="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {visibleRoutes.map(([name, path]) => (
            <div
              key={name}
              className="animate-in fade-in duration-300 transition-all hover:-translate-y-1"
            >
              <Link href={`/${path}`} className="group block h-full">
                <Card className="h-full gap-4 transition-colors group-hover:border-primary/50 shadow-sm hover:shadow-md">
                  <CardHeader>
                    <div className="flex items-center justify-between gap-2">
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted text-foreground transition-colors group-hover:bg-primary/10 group-hover:text-primary">
                        <Sparkles className="h-5 w-5" />
                      </div>
                      <Badge variant="secondary">{counts[name] ?? "…"} records</Badge>
                    </div>
                    <CardTitle className="capitalize transition-colors group-hover:text-primary">
                      {name.replaceAll("_", " ")}
                    </CardTitle>
                    <CardDescription>
                      Access data records, creation forms, and API actions for{" "}
                      {name.replaceAll("_", " ")}.
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="mt-auto flex items-center justify-between border-t border-border pt-4 text-xs font-semibold text-primary">
                    <span>Manage {name.replaceAll("_", " ")}</span>
                    <span className="transition-transform group-hover:translate-x-1">→</span>
                  </CardContent>
                </Card>
              </Link>
            </div>
          ))}
        </div>
        )}
      </div>
    </main>
  );
}
