# @generated by AI Solution Builder
"""API routers — CRUD GENERATED from spec.json. Business logic lives in actions.py."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException
from sqlalchemy import select, text

try:
    from . import models, schemas
    from .actions import router as actions_router
    from .core.config import settings
    from .deps import SessionDep
    try:
        from .routers_analytics import router as analytics_router
    except (ImportError, ValueError):
        analytics_router = None
except (ImportError, ValueError):
    import models
    import schemas
    from actions import router as actions_router
    from core.config import settings
    from deps import SessionDep
    try:
        from routers_analytics import router as analytics_router
    except (ImportError, ValueError):
        analytics_router = None

router = APIRouter()


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "service": settings.APP_NAME}


@router.get("/ready")
async def ready(session: SessionDep) -> dict[str, str]:
    await session.execute(text("SELECT 1"))
    return {"status": "ready", "database": "ok"}


async def _check_refs_invoices(session: SessionDep, data: dict) -> None:
    return None


@router.get("/invoices", response_model=list[schemas.InvoicesRead], tags=["invoices"])
async def list_invoices(session: SessionDep) -> list:
    q = select(models.Invoices).order_by(models.Invoices.id)
    return list((await session.execute(q)).scalars().all())


@router.post("/invoices", response_model=schemas.InvoicesRead, status_code=201, tags=["invoices"])
async def create_invoices(payload: schemas.InvoicesCreate, session: SessionDep):
    data = payload.model_dump()
    await _check_refs_invoices(session, data)
    obj = models.Invoices(**data)
    session.add(obj)
    await session.commit()
    await session.refresh(obj)
    return obj


@router.get("/invoices/{item_id}", response_model=schemas.InvoicesRead, tags=["invoices"])
async def get_invoices(item_id: int, session: SessionDep):
    obj = await session.get(models.Invoices, item_id)
    if obj is None:
        raise HTTPException(404, "invoices not found")
    return obj


@router.patch("/invoices/{item_id}", response_model=schemas.InvoicesRead, tags=["invoices"])
async def update_invoices(item_id: int, payload: schemas.InvoicesUpdate, session: SessionDep):
    obj = await session.get(models.Invoices, item_id)
    if obj is None:
        raise HTTPException(404, "invoices not found")
    data = payload.model_dump(exclude_unset=True)
    await _check_refs_invoices(session, data)
    for k, v in data.items():
        setattr(obj, k, v)
    await session.commit()
    await session.refresh(obj)
    return obj


@router.delete("/invoices/{item_id}", tags=["invoices"])
async def delete_invoices(item_id: int, session: SessionDep) -> dict:
    obj = await session.get(models.Invoices, item_id)
    if obj is None:
        raise HTTPException(404, "invoices not found")
    await session.delete(obj)
    await session.commit()
    return {"deleted": True}

async def _check_refs_expenses(session: SessionDep, data: dict) -> None:
    return None


@router.get("/expenses", response_model=list[schemas.ExpensesRead], tags=["expenses"])
async def list_expenses(session: SessionDep) -> list:
    q = select(models.Expenses).order_by(models.Expenses.id)
    return list((await session.execute(q)).scalars().all())


@router.post("/expenses", response_model=schemas.ExpensesRead, status_code=201, tags=["expenses"])
async def create_expenses(payload: schemas.ExpensesCreate, session: SessionDep):
    data = payload.model_dump()
    await _check_refs_expenses(session, data)
    obj = models.Expenses(**data)
    session.add(obj)
    await session.commit()
    await session.refresh(obj)
    return obj


@router.get("/expenses/{item_id}", response_model=schemas.ExpensesRead, tags=["expenses"])
async def get_expenses(item_id: int, session: SessionDep):
    obj = await session.get(models.Expenses, item_id)
    if obj is None:
        raise HTTPException(404, "expenses not found")
    return obj


@router.patch("/expenses/{item_id}", response_model=schemas.ExpensesRead, tags=["expenses"])
async def update_expenses(item_id: int, payload: schemas.ExpensesUpdate, session: SessionDep):
    obj = await session.get(models.Expenses, item_id)
    if obj is None:
        raise HTTPException(404, "expenses not found")
    data = payload.model_dump(exclude_unset=True)
    await _check_refs_expenses(session, data)
    for k, v in data.items():
        setattr(obj, k, v)
    await session.commit()
    await session.refresh(obj)
    return obj


@router.delete("/expenses/{item_id}", tags=["expenses"])
async def delete_expenses(item_id: int, session: SessionDep) -> dict:
    obj = await session.get(models.Expenses, item_id)
    if obj is None:
        raise HTTPException(404, "expenses not found")
    await session.delete(obj)
    await session.commit()
    return {"deleted": True}

router.include_router(actions_router)
if analytics_router is not None:
    router.include_router(analytics_router)
