# @generated by AI Solution Builder
"""API routers — CRUD GENERATED from spec.json. Business logic lives in actions.py."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException
from sqlalchemy import select, text

try:
    from . import models, schemas
    from .actions import router as actions_router
    from .core.config import settings
    from .deps import SessionDep
    try:
        from .routers_analytics import router as analytics_router
    except (ImportError, ValueError):
        analytics_router = None
except (ImportError, ValueError):
    import models
    import schemas
    from actions import router as actions_router
    from core.config import settings
    from deps import SessionDep
    try:
        from routers_analytics import router as analytics_router
    except (ImportError, ValueError):
        analytics_router = None

router = APIRouter()


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "service": settings.APP_NAME}


@router.get("/ready")
async def ready(session: SessionDep) -> dict[str, str]:
    await session.execute(text("SELECT 1"))
    return {"status": "ready", "database": "ok"}


async def _check_refs_subscription(session: SessionDep, data: dict) -> None:
    return None


@router.get("/subscriptions", response_model=list[schemas.SubscriptionRead], tags=["subscriptions"])
async def list_subscriptions(session: SessionDep) -> list:
    q = select(models.Subscription).order_by(models.Subscription.id)
    return list((await session.execute(q)).scalars().all())


@router.post("/subscriptions", response_model=schemas.SubscriptionRead, status_code=201, tags=["subscriptions"])
async def create_subscription(payload: schemas.SubscriptionCreate, session: SessionDep):
    data = payload.model_dump()
    await _check_refs_subscription(session, data)
    obj = models.Subscription(**data)
    session.add(obj)
    await session.commit()
    await session.refresh(obj)
    return obj


@router.get("/subscriptions/{item_id}", response_model=schemas.SubscriptionRead, tags=["subscriptions"])
async def get_subscription(item_id: int, session: SessionDep):
    obj = await session.get(models.Subscription, item_id)
    if obj is None:
        raise HTTPException(404, "subscription not found")
    return obj


@router.patch("/subscriptions/{item_id}", response_model=schemas.SubscriptionRead, tags=["subscriptions"])
async def update_subscription(item_id: int, payload: schemas.SubscriptionUpdate, session: SessionDep):
    obj = await session.get(models.Subscription, item_id)
    if obj is None:
        raise HTTPException(404, "subscription not found")
    data = payload.model_dump(exclude_unset=True)
    await _check_refs_subscription(session, data)
    for k, v in data.items():
        setattr(obj, k, v)
    await session.commit()
    await session.refresh(obj)
    return obj


@router.delete("/subscriptions/{item_id}", tags=["subscriptions"])
async def delete_subscription(item_id: int, session: SessionDep) -> dict:
    obj = await session.get(models.Subscription, item_id)
    if obj is None:
        raise HTTPException(404, "subscription not found")
    await session.delete(obj)
    await session.commit()
    return {"deleted": True}

router.include_router(actions_router)
if analytics_router is not None:
    router.include_router(analytics_router)
