# @generated by AI Solution Builder
"""Pydantic schemas — GENERATED from spec.json. Do not edit by hand."""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict


class InvoicesCreate(BaseModel):
    client_name: str
    amount: str
    issued_on: str


class InvoicesUpdate(BaseModel):
    client_name: str | None = None
    amount: str | None = None
    issued_on: str | None = None


class InvoicesRead(InvoicesCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_at: datetime


class ExpensesCreate(BaseModel):
    description: str
    amount: str
    incurred_on: str


class ExpensesUpdate(BaseModel):
    description: str | None = None
    amount: str | None = None
    incurred_on: str | None = None


class ExpensesRead(ExpensesCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_at: datetime
