# @generated by AI Solution Builder
"""Pydantic schemas — GENERATED from spec.json. Do not edit by hand."""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict


class SubscriptionCreate(BaseModel):
    name: str
    cost: float
    billing_cycle: str
    renewal_date: date
    category: str
    status: str


class SubscriptionUpdate(BaseModel):
    name: str | None = None
    cost: float | None = None
    billing_cycle: str | None = None
    renewal_date: date | None = None
    category: str | None = None
    status: str | None = None


class SubscriptionRead(SubscriptionCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_at: datetime
