# @generated by AI Solution Builder
"""Pydantic schemas — GENERATED from spec.json. Do not edit by hand."""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict


class InvoiceCreate(BaseModel):
    client_name: str
    amount: float
    issued_on: date


class InvoiceUpdate(BaseModel):
    client_name: str | None = None
    amount: float | None = None
    issued_on: date | None = None


class InvoiceRead(InvoiceCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_at: datetime


class ExpenseCreate(BaseModel):
    description: str
    amount: float
    incurred_on: date


class ExpenseUpdate(BaseModel):
    description: str | None = None
    amount: float | None = None
    incurred_on: date | None = None


class ExpenseRead(ExpenseCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_at: datetime
