# @generated by AI Solution Builder
"""Example rows for a brand-new, empty app.

Only runs when a table is completely empty, so your own records are safe.
"""

from __future__ import annotations

import asyncio

from sqlalchemy import func, select

try:
    from .db import AsyncSessionLocal, engine
    from .models import Base
    from . import models
except (ImportError, ValueError):
    from db import AsyncSessionLocal, engine
    from models import Base
    import models


SEED: dict[str, list[dict]] = {
}


MODELS = {
    'invoice': models.Invoice,
    'expense': models.Expense,
}


async def seed() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    async with AsyncSessionLocal() as session:
        for name, rows in SEED.items():
            model = MODELS.get(name)
            if model is None or not rows:
                continue
            existing = await session.scalar(select(func.count()).select_from(model))
            if existing:
                continue
            for row in rows:
                session.add(model(**row))
        await session.commit()


if __name__ == "__main__":
    asyncio.run(seed())
