# @generated by AI Solution Builder
"""Acceptance tests GENERATED from spec.json — the definition of done. Do not edit."""

import pytest

from conftest import run_steps

pytestmark = pytest.mark.asyncio


async def test_create_subscription(client):
    """A new subscription can be created via POST"""
    steps = [
    {
        "method": "POST",
        "path": "/subscriptions",
        "body": {
            "name": "Sample Value",
            "cost": 10.0,
            "billing_cycle": "Sample Value",
            "renewal_date": "Sample Value",
            "category": "Sample Value",
            "status": "Sample Value"
        },
        "expect_status": 201,
        "expect": {
            "name": "Sample Value",
            "cost": 10.0,
            "billing_cycle": "Sample Value",
            "renewal_date": "Sample Value",
            "category": "Sample Value",
            "status": "Sample Value"
        },
        "save": {
            "id": "id"
        }
    }
]
    await run_steps(client, steps)


async def test_list_subscriptions(client):
    """Listing subscriptions returns HTTP 200"""
    steps = [
    {
        "method": "GET",
        "path": "/subscriptions",
        "expect_status": 200,
        "expect": {},
        "save": {}
    }
]
    await run_steps(client, steps)


async def test_get_subscription(client):
    """A single subscription can be created and retrieved by ID"""
    steps = [
    {
        "method": "POST",
        "path": "/subscriptions",
        "body": {
            "name": "Sample Value",
            "cost": 10.0,
            "billing_cycle": "Sample Value",
            "renewal_date": "Sample Value",
            "category": "Sample Value",
            "status": "Sample Value"
        },
        "expect_status": 201,
        "expect": {},
        "save": {
            "id": "id"
        }
    },
    {
        "method": "GET",
        "path": "/subscriptions/{id}",
        "expect_status": 200,
        "expect": {},
        "save": {}
    }
]
    await run_steps(client, steps)
