# @generated by AI Solution Builder
"""Acceptance tests GENERATED from spec.json — the definition of done. Do not edit."""

import pytest

from conftest import run_steps

pytestmark = pytest.mark.asyncio


async def test_create_invoices(client):
    """A new invoices can be created via POST"""
    steps = [
    {
        "method": "POST",
        "path": "/invoices",
        "body": {
            "client_name": "Sample Value",
            "amount": "Sample Value",
            "issued_on": "Sample Value"
        },
        "expect_status": 201,
        "expect": {
            "client_name": "Sample Value",
            "amount": "Sample Value",
            "issued_on": "Sample Value"
        },
        "save": {
            "id": "id"
        }
    }
]
    await run_steps(client, steps)


async def test_list_invoices(client):
    """Listing invoices returns HTTP 200"""
    steps = [
    {
        "method": "GET",
        "path": "/invoices",
        "expect_status": 200,
        "expect": {},
        "save": {}
    }
]
    await run_steps(client, steps)


async def test_get_invoices(client):
    """A single invoices can be created and retrieved by ID"""
    steps = [
    {
        "method": "POST",
        "path": "/invoices",
        "body": {
            "client_name": "Sample Value",
            "amount": "Sample Value",
            "issued_on": "Sample Value"
        },
        "expect_status": 201,
        "expect": {},
        "save": {
            "id": "id"
        }
    },
    {
        "method": "GET",
        "path": "/invoices/{id}",
        "expect_status": 200,
        "expect": {},
        "save": {}
    }
]
    await run_steps(client, steps)
