// @generated by AI Solution Builder (non-destructive)
"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import type { Expenses as ExpensesType } from "@/lib/types";
import { api } from "@/lib/api";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Plus, ArrowLeft, Trash2, Search, CheckCircle2, AlertCircle, RefreshCw } from "lucide-react";

export default function ExpensesPage() {
  const [rows, setRows] = useState<ExpensesType[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [form, setForm] = useState<Record<string, string | boolean>>({});
  const [showDrawer, setShowDrawer] = useState(false);
  const [search, setSearch] = useState("");

  const load = useCallback(async () => {
    try {
      setLoading(true);
      setError("");
      setRows(await api.get<ExpensesType[]>("/expenses"));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load expenses");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const create = async () => {
    try {
      const body: Record<string, unknown> = {};
            body["description"] = String(form["description"] ?? "");
      body["amount"] = String(form["amount"] ?? "");
      body["incurred_on"] = String(form["incurred_on"] ?? "");
      await api.post<ExpensesType>("/expenses", body);
      setForm({});
      setShowDrawer(false);
      setNotice("Expenses created successfully!");
      setTimeout(() => setNotice(""), 3000);
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create record");
    }
  };

  const remove = async (id: number) => {
    if (!window.confirm("Are you sure you want to delete this record?")) return;
    try {
      await api.del(`/expenses/${id}`);
      setNotice("Record deleted successfully.");
      setTimeout(() => setNotice(""), 3000);
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete record");
    }
  };

  const field = (name: string) => (form[name] ?? "") as string | boolean;

  const set = (name: string, value: string | boolean) =>
    setForm((f) => ({ ...f, [name]: value }));

  const filteredRows = rows.filter((r) => {
    if (!search.trim()) return true;
    return JSON.stringify(r).toLowerCase().includes(search.toLowerCase());
  });

  return (
    <main className="min-h-screen bg-background px-4 py-8 text-foreground sm:px-6 md:py-12">
      <div className="mx-auto max-w-6xl">
        {/* Navigation Breadcrumb & Actions */}
        <div className="flex items-center justify-between gap-2">
          <Button asChild variant="ghost" size="sm" className="text-muted-foreground">
            <Link href="/">
              <ArrowLeft className="h-3.5 w-3.5" />
              Back to Dashboard
            </Link>
          </Button>

          <Badge variant="secondary">Module: expenses</Badge>
        </div>

        {/* Header Hero */}
        <div className="mt-4 animate-in fade-in duration-300">
          <Card>
            <CardHeader>
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="min-w-0">
                  <CardTitle className="text-2xl md:text-3xl">Expenses</CardTitle>
                  <CardDescription className="mt-1">Manage expenses</CardDescription>
                </div>

                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="icon"
                    onClick={() => void load()}
                    title="Refresh records"
                    aria-label="Refresh records"
                  >
                    <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
                  </Button>
                  <Button onClick={() => setShowDrawer(true)}>
                    <Plus className="h-4 w-4" />
                    New Expenses
                  </Button>
                </div>
              </div>
            </CardHeader>
          </Card>
        </div>

        {/* Notices and Alerts */}
        {notice && (
          <div className="mt-4 animate-in fade-in duration-200">
            <Alert>
              <CheckCircle2 className="h-4 w-4" />
              <AlertDescription>{notice}</AlertDescription>
            </Alert>
          </div>
        )}
        {error && (
          <div className="mt-4 animate-in fade-in duration-200">
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          </div>
        )}

        {/* Data Management Section */}
        <section className="mt-8 animate-in fade-in duration-300">
          <Card>
            <CardHeader>
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div>
                  <CardTitle>Registered Records</CardTitle>
                  <CardDescription>
                    {rows.length} total entries recorded in database
                  </CardDescription>
                </div>

                <div className="relative w-full max-w-xs">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    type="text"
                    placeholder="Filter records..."
                    aria-label="Filter records"
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="pl-9"
                  />
                </div>
              </div>
            </CardHeader>

            <CardContent>
              {/* A table of records has to stay usable on a phone, so the
                  wrapper scrolls horizontally instead of forcing the page wide. */}
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-24">ID</TableHead>
                      <TableHead className="px-3 py-2">Description</TableHead>
                <TableHead className="px-3 py-2">Amount</TableHead>
                <TableHead className="px-3 py-2">Incurred On</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredRows.map((row) => (
                      <TableRow key={row.id}>
                        <TableCell className="font-mono text-xs text-muted-foreground">
                          {String(row.id).slice(0, 8)}
                        </TableCell>
                        <TableCell className="px-3 py-2">{String(row.description ?? "—")}</TableCell>
                  <TableCell className="px-3 py-2">{String(row.amount ?? "—")}</TableCell>
                  <TableCell className="px-3 py-2">{String(row.incurred_on ?? "—")}</TableCell>
                        <TableCell className="text-right">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => void remove(row.id)}
                            title="Delete record"
                            className="text-destructive hover:text-destructive"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                            <span className="sr-only sm:not-sr-only">Delete</span>
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>

              {loading && (
                <div className="space-y-2 py-6">
                  {[0, 1, 2].map((i) => (
                    <Skeleton key={i} className="h-9 w-full" />
                  ))}
                </div>
              )}

              {!loading && filteredRows.length === 0 && (
                <div className="flex flex-col items-center gap-2 py-12 text-center">
                  <Search className="h-6 w-6 text-muted-foreground" />
                  <CardTitle className="text-base">No records found</CardTitle>
                  <CardDescription>
                    {search
                      ? "No records match your filter."
                      : "Get started by creating your first record."}
                  </CardDescription>
                  <Button className="mt-2" size="sm" onClick={() => setShowDrawer(true)}>
                    <Plus className="h-4 w-4" />
                    Create First Record
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </section>

        {/* Slide-over Create Record Drawer */}
        {showDrawer && (
          <div className="fixed inset-0 z-50 flex justify-end">
            <div
              onClick={() => setShowDrawer(false)}
              className="fixed inset-0 bg-foreground/40 backdrop-blur-sm animate-in fade-in duration-200"
            />

            <div
              className="relative z-10 w-full max-w-md overflow-y-auto border-l border-border bg-background p-6 shadow-2xl animate-in slide-in-from-right duration-300"
              role="dialog"
              aria-modal="true"
              aria-label="New Expenses"
            >
              <div className="flex items-start justify-between gap-2 border-b border-border pb-4">
                <div>
                  <h3 className="text-lg font-bold text-foreground">New Expenses</h3>
                  <p className="text-xs text-muted-foreground">
                    Fill in the fields to create a record
                  </p>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => setShowDrawer(false)}
                  aria-label="Close"
                >
                  <ArrowLeft className="h-4 w-4 rotate-90" />
                </Button>
              </div>

              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  void create();
                }}
                className="mt-6 space-y-4"
              >
                <div className="flex flex-col gap-2">
          <Label htmlFor="description">Description</Label>
          <Input id="description" type="text" value={String(field("description") ?? "")} onChange={(e) => set("description", e.target.value)} />
        </div>
          <div className="flex flex-col gap-2">
          <Label htmlFor="amount">Amount</Label>
          <Input id="amount" type="text" value={String(field("amount") ?? "")} onChange={(e) => set("amount", e.target.value)} />
        </div>
          <div className="flex flex-col gap-2">
          <Label htmlFor="incurred_on">Incurred On</Label>
          <Input id="incurred_on" type="text" value={String(field("incurred_on") ?? "")} onChange={(e) => set("incurred_on", e.target.value)} />
        </div>

                <div className="flex items-center justify-end gap-2 border-t border-border pt-6">
                  <Button
                    type="button"
                    variant="ghost"
                    onClick={() => setShowDrawer(false)}
                  >
                    Cancel
                  </Button>
                  <Button type="submit">Save Record</Button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
