// @generated by AI Solution Builder
// GENERATED from spec.json. CRUD base path: /{plural}; actions under /actions/.

export interface Subscription {
  id: number;
  name: string;
  cost: number;
  billing_cycle: string;
  renewal_date: string;
  category: string;
  status: string;
  created_at: string;
}

export type BillingCycle = "weekly" | "monthly" | "yearly";

export interface Subscription {
  id: number;
  name: string;
  cost: number;
  billing_cycle: BillingCycle;
  next_renewal: string;
  created_at: string;
}

export interface SubscriptionSummary {
  total_monthly: number;
  total_annual: number;
  active_count: number;
  renewing_soon: number;
}

export const ENDPOINTS = {
  "subscription": "/subscriptions"
} as const;
