// @generated by AI Solution Builder
// GENERATED from spec.json. CRUD base path: /{plural}; actions under /actions/.

export interface Invoices {
  id: number;
  client_name: string;
  amount: string;
  issued_on: string;
  created_at: string;
}

export interface Expenses {
  id: number;
  description: string;
  amount: string;
  incurred_on: string;
  created_at: string;
}

export const ENDPOINTS = {
  "invoices": "/invoices",
  "expenses": "/expenses"
} as const;
