// @generated by AI Solution Builder
// GENERATED from spec.json. CRUD base path: /{plural}; actions under /actions/.

export interface Invoice {
  id: number;
  client_name: string;
  amount: number;
  issued_on: string;
  created_at: string;
}

export interface Expense {
  id: number;
  description: string;
  amount: number;
  incurred_on: string;
  created_at: string;
}

export const ENDPOINTS = {
  "invoice": "/invoices",
  "expense": "/expenses"
} as const;
